sudo: required
services:
  - docker

before_install:
  # dockerid/name_of_your_image
  - docker build -t rooch/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rooch/react-test npm test -- --coverage

after_success:
  - docker build -t rooch/multi-images-client ./client
  - docker build -t rooch/multi-images-nginx ./nginx
  - docker build -t rooch/multi-images-server ./server
  - docker build -t rooch/multi-images-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rooch/multi-images-client
  - docker push rooch/multi-images-nginx
  - docker push rooch/multi-images-server
  - docker push rooch/multi-images-worker

  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker 
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-484587301471
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
   

